#!/usr/bin/env python3
from __future__ import annotations

# this is the single-run onset metric script
# it assumes tracking already happened, then compares video subharmonic growth
# with the accelerometer gamma envelope so we can manually pick onset later

import argparse
import json
import sys
from pathlib import Path

# add scripts folders to the import path so this can run as a plain script
_SCRIPT_ROOT = Path(__file__).resolve().parents[2] / "scripts"
for _script_dir in (_SCRIPT_ROOT, *_SCRIPT_ROOT.glob("*")):
    if _script_dir.is_dir() and str(_script_dir) not in sys.path:
        sys.path.insert(0, str(_script_dir))
from typing import Any

import matplotlib

# use non-interactive matplotlib, this script only saves pngs
matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
DOT_TRACKING_DIR = PROJECT_ROOT / "scripts" / "dot_tracking"
if str(DOT_TRACKING_DIR) in sys.path:
    sys.path.remove(str(DOT_TRACKING_DIR))
# put dot_tracking first so "common" means dot_tracking/common.py
# those helpers know about repo-relative paths and metadata yaml
sys.path.insert(0, str(DOT_TRACKING_DIR))

from common import (  # noqa: E402
    load_yaml,
    project_path,
    relpath,
    summarize_timebase,
    write_json,
)
from accelerometer.common import (  # noqa: E402
    analyze_accelerometer,
    median_dt_seconds,
    rolling_sum_centered_2d,
)


# cli inputs for one run
# this script does not track dots, it consumes tracking npz + accel csvs
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Compute run-up onset metrics from frequency-style tracked dots and "
            "accelerometer data."
        )
    )
    parser.add_argument("--run-metadata", required=True, help="Run metadata YAML generated by the batch pipeline.")
    parser.add_argument(
        "--tracking-npz",
        required=True,
        help="Existing tracked_dots_frequency.npz produced by frequency dot tracking.",
    )
    # run-up csv has the actual forcing ramp
    # calibration csv estimates accelerometer bias/background
    parser.add_argument("--runup-accel-csv", required=True)
    parser.add_argument("--calibration-accel-csv", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument(
        "--video-frequency-source",
        choices=("accelerometer", "nominal"),
        default="accelerometer",
        help=(
            "Frequency used for the video subharmonic lock-in band. The default uses "
            "the accelerometer drive-band peak; nominal uses the drive frequency "
            "and expected subharmonic stored in run metadata."
        ),
    )
    parser.add_argument(
        "--baseline-video-seconds",
        type=float,
        default=2.0,
        help="Initial flat-liquid interval used to estimate video baseline noise.",
    )
    parser.add_argument("--subharmonic-half-width-hz", type=float, default=1.5)
    parser.add_argument("--frequency-step-hz", type=float, default=0.05)
    parser.add_argument(
        "--lockin-window-s",
        type=float,
        default=1.0,
        help="Centered lock-in averaging window for video subharmonic envelope.",
    )
    parser.add_argument(
        "--min-valid-dot-fraction",
        type=float,
        default=0.60,
        help="Dots valid in less than this fraction of frames are excluded from onset analysis.",
    )
    parser.add_argument(
        "--accel-lockin-window-s",
        type=float,
        default=1.0,
        help="Centered lock-in window for acceleration gamma envelope.",
    )
    parser.add_argument(
        "--accel-time-offset-s",
        type=float,
        default=0.0,
        help="Add this offset to accelerometer time before matching video time.",
    )
    parser.add_argument(
        "--accel-auto-search-min-hz",
        type=float,
        default=2.0,
        help="Minimum accelerometer spectral search frequency.",
    )
    parser.add_argument(
        "--accel-auto-search-max-hz",
        type=float,
        default=80.0,
        help="Maximum accelerometer spectral search frequency.",
    )
    return parser.parse_args()


# choose the drive/subharmonic frequency used for video lock-in
# ideally use measured accelerometer drive, otherwise fall back to metadata
def choose_analysis_frequencies(
    *,
    nominal_drive_hz: float,
    nominal_expected_subharmonic_hz: float,
    measured_drive_hz: float,
    source: str,
) -> dict[str, Any]:
    # if measured drive failed, still let the run finish using nominal values
    measured_ok = np.isfinite(measured_drive_hz) and measured_drive_hz > 0
    if source == "accelerometer" and measured_ok:
        # preferred path, center everything on the actual accelerometer peak
        analysis_drive_hz = float(measured_drive_hz)
        analysis_expected_subharmonic_hz = 0.5 * analysis_drive_hz
        frequency_source = "accelerometer_drive_band_peak"
        fallback_used = False
    else:
        analysis_drive_hz = float(nominal_drive_hz)
        analysis_expected_subharmonic_hz = float(nominal_expected_subharmonic_hz)
        frequency_source = "nominal_metadata"
        fallback_used = source == "accelerometer"
    return {
        "nominal_drive_hz": float(nominal_drive_hz),
        "nominal_expected_subharmonic_hz": float(nominal_expected_subharmonic_hz),
        "measured_drive_hz": float(measured_drive_hz) if measured_ok else float("nan"),
        "analysis_drive_hz": analysis_drive_hz,
        "analysis_expected_subharmonic_hz": analysis_expected_subharmonic_hz,
        "source": frequency_source,
        "requested_source": str(source),
        "fallback_used": bool(fallback_used),
    }


# load tracking npz and clean it for onset analysis
# keep good dots, subtract early baseline, remove frame-mean motion
def load_tracking_displacements(
    tracking_npz: Path,
    *,
    min_valid_dot_fraction: float,
    baseline_seconds: float,
) -> dict[str, Any]:
    with np.load(tracking_npz, allow_pickle=False) as data:
        # corrected_dxy_px is frames x dots x xy
        # track_frequency_dots already removed global affine motion
        time_s = data["time_s"].astype(float)
        frame_indices = data["frame_indices"].astype(int)
        valid = data["valid"].astype(bool)
        dxy = data["corrected_dxy_px"].astype(np.float32)
        dot_spacing_px = float(data["dot_spacing_px"])
        match_score = data["match_score"].astype(float) if "match_score" in data.files else None

    # start video time at 0 for this run
    time_s = time_s - time_s[0]
    dot_valid_fraction = np.mean(valid, axis=0)
    # remove dots that failed too often
    keep = dot_valid_fraction >= float(min_valid_dot_fraction)
    if int(np.sum(keep)) < 30:
        # if too few survive, keep the best dots instead of failing the run
        order = np.argsort(dot_valid_fraction)[::-1]
        keep = np.zeros_like(dot_valid_fraction, dtype=bool)
        keep[order[: min(200, len(order))]] = True

    valid = valid[:, keep]
    dxy = dxy[:, keep, :]
    if match_score is not None:
        match_score = match_score[:, keep]

    baseline_mask = time_s <= float(baseline_seconds)
    if int(np.sum(baseline_mask)) < 5:
        # if baseline interval is too short, just use the first few frames
        baseline_mask = np.arange(len(time_s)) < min(30, len(time_s))

    dxy_masked = np.where(valid[:, :, None], dxy, np.nan)
    # subtract each dot's early baseline so static template offsets don't count as motion
    baseline_center = np.nanmedian(dxy_masked[baseline_mask], axis=0, keepdims=True)
    dxy0 = dxy_masked - baseline_center

    # remove the average displacement of all dots in a frame
    # this keeps the metric focused on relative deformation, not drift
    frame_mean = np.nanmean(dxy0, axis=1, keepdims=True)
    dxy0 = dxy0 - frame_mean
    dxy0 = np.where(np.isfinite(dxy0), dxy0, 0.0).astype(np.float32)

    valid_fraction_frame = np.mean(valid, axis=1)
    rms = np.sqrt(
        np.nanmean(
            np.where(valid, np.sum(dxy0**2, axis=2), np.nan),
            axis=1,
        )
    )

    return {
        "time_s": time_s,
        "frame_indices": frame_indices,
        "valid": valid,
        "dxy_px": dxy0,
        "dot_spacing_px": dot_spacing_px,
        "dots_total_after_filter": int(valid.shape[1]),
        "valid_fraction_frame": valid_fraction_frame,
        "rms_displacement_px": rms,
        "match_score": match_score,
    }


# video lock-in around the subharmonic band
# for each test frequency, demodulate dot motion and average locally in time
def lockin_band_power(
    *,
    dxy_px: np.ndarray,
    valid: np.ndarray,
    times_s: np.ndarray,
    frequencies_hz: np.ndarray,
    window_s: float,
    chunk_features: int = 512,
) -> np.ndarray:
    times = np.asarray(times_s, dtype=float)
    dt = median_dt_seconds(times)
    if not np.isfinite(dt) or dt <= 0:
        raise ValueError("Cannot estimate video sample spacing for lock-in analysis.")
    window = max(3, int(round(float(window_s) / dt)))
    if window % 2 == 0:
        window += 1

    # treat x and y motion as separate signals
    # one dot gives two features
    ux = dxy_px[:, :, 0]
    uy = dxy_px[:, :, 1]
    x = np.concatenate([ux, uy], axis=1).astype(np.float32)
    w = np.concatenate([valid, valid], axis=1).astype(np.float32)
    x = np.where(w > 0, x, 0.0)

    n_t, n_features = x.shape
    power = np.full((n_t, len(frequencies_hz)), np.nan, dtype=np.float32)
    # chunk features so memory stays reasonable
    chunks = [(start, min(start + chunk_features, n_features)) for start in range(0, n_features, chunk_features)]
    # denominators count valid samples inside each rolling window
    denom_chunks = [
        rolling_sum_centered_2d(w[:, start:stop], window).astype(np.float32)
        for start, stop in chunks
    ]

    for f_pos, freq in enumerate(frequencies_hz):
        # demodulate at this test frequency
        # if the dot really moves at this frequency, it becomes a slow complex signal
        basis = np.exp(-2j * np.pi * float(freq) * times).astype(np.complex64)
        sum_power = np.zeros(n_t, dtype=np.float64)
        count = np.zeros(n_t, dtype=np.float64)
        for chunk_pos, (start, stop) in enumerate(chunks):
            xc = x[:, start:stop] * w[:, start:stop]
            denom = denom_chunks[chunk_pos]
            # rolling sum estimates the local lock-in coefficient
            numerator = rolling_sum_centered_2d(xc.astype(np.complex64) * basis[:, None], window)
            # reject windows with too many missing tracking samples
            usable = denom >= max(3.0, 0.25 * window)
            coeff = np.zeros_like(numerator, dtype=np.complex64)
            coeff[usable] = numerator[usable] / denom[usable]
            # power = coefficient magnitude squared, averaged over features
            amp2 = np.abs(coeff) ** 2
            sum_power += np.sum(np.where(usable, amp2, 0.0), axis=1)
            count += np.sum(usable, axis=1)
        with np.errstate(invalid="ignore", divide="ignore"):
            power[:, f_pos] = (sum_power / count).astype(np.float32)

    return power


# saved heatmap for manual review of subharmonic-band power over time
def plot_lockin_map(
    path: Path,
    *,
    time_s: np.ndarray,
    freqs_hz: np.ndarray,
    power: np.ndarray,
    best_freq_hz: np.ndarray,
    expected_hz: float,
) -> None:
    # add a floor before log10 so zeros don't become -inf
    eps = np.nanpercentile(power[np.isfinite(power)], 5) if np.any(np.isfinite(power)) else 1e-12
    eps = max(float(eps), 1e-12)
    image = np.log10(power.T + eps)
    fig, ax = plt.subplots(figsize=(11, 5.2))
    im = ax.imshow(
        image,
        origin="lower",
        aspect="auto",
        extent=[float(time_s[0]), float(time_s[-1]), float(freqs_hz[0]), float(freqs_hz[-1])],
        cmap="viridis",
    )
    ax.plot(time_s, best_freq_hz, color="w", lw=0.9, alpha=0.8, label="best local frequency")
    ax.axhline(expected_hz, color="tab:red", ls="--", lw=1.0, label=f"expected {expected_hz:.2f} Hz")
    ax.set_xlabel("video time [s]")
    ax.set_ylabel("frequency [Hz]")
    ax.legend(loc="upper right")
    fig.colorbar(im, ax=ax, label="log10 lock-in power [px^2]")
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


# saved summary plot, video response and gamma together
def plot_synchronized_summary(
    path: Path,
    *,
    video_time_s: np.ndarray,
    envelope_px: np.ndarray,
    exact_envelope_px: np.ndarray,
    best_frequency_hz: np.ndarray,
    expected_hz: float,
    accel_time_s: np.ndarray,
    gamma_g: np.ndarray,
) -> None:
    def normalize(values: np.ndarray) -> np.ndarray:
        # only for plotting, does not change saved csv values
        finite = values[np.isfinite(values)]
        if finite.size == 0:
            return np.full_like(values, np.nan, dtype=float)
        lo, hi = float(np.nanpercentile(finite, 5)), float(np.nanpercentile(finite, 99))
        if not np.isfinite(hi - lo) or hi <= lo:
            return np.zeros_like(values, dtype=float)
        return np.clip((values - lo) / (hi - lo), 0, 1)

    fig, axes = plt.subplots(3, 1, figsize=(11.5, 9.0), sharex=True)
    axes[0].plot(video_time_s, envelope_px, lw=1.3, label="max subharmonic-band envelope")
    axes[0].plot(video_time_s, exact_envelope_px, lw=1.0, alpha=0.75, label=f"envelope at {expected_hz:.2f} Hz")
    axes[0].set_ylabel("video envelope [px]")
    axes[0].grid(True, alpha=0.3)
    axes[0].legend(loc="upper left")

    axes[1].plot(accel_time_s, gamma_g, lw=1.2, color="tab:orange", label="accelerometer gamma envelope")
    axes[1].set_ylabel(r"$\Gamma=a/g$")
    axes[1].grid(True, alpha=0.3)
    axes[1].legend(loc="upper left")

    axes[2].plot(video_time_s, normalize(envelope_px), lw=1.2, label="normalized video envelope")
    axes[2].plot(accel_time_s, normalize(gamma_g), lw=1.1, label="normalized gamma")
    axes[2].plot(video_time_s, best_frequency_hz / expected_hz, lw=0.9, alpha=0.7, label="best frequency / expected")
    axes[2].axhline(1.0, color="k", ls=":", lw=0.9)
    axes[2].set_xlabel("time [s]")
    axes[2].set_ylabel("normalized")
    axes[2].grid(True, alpha=0.3)
    axes[2].legend(loc="upper left")
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


# metadata helpers for nominal drive and expected f/2
def metadata_drive_hz(run_metadata: dict[str, Any]) -> float:
    experiment = run_metadata.get("experiment", {})
    drive = run_metadata.get("drive", {})
    value = (
        experiment.get("drive_frequency_hz")
        or drive.get("measured_frequency_hz")
        or drive.get("nominal_frequency_hz")
    )
    if value is None:
        raise ValueError("Run metadata is missing experiment.drive_frequency_hz.")
    return float(value)


def metadata_expected_subharmonic_hz(run_metadata: dict[str, Any], drive_hz: float) -> float:
    experiment = run_metadata.get("experiment", {})
    drive = run_metadata.get("drive", {})
    value = experiment.get("expected_subharmonic_hz") or drive.get("expected_subharmonic_hz")
    return float(value) if value is not None else 0.5 * float(drive_hz)


def main() -> None:
    args = parse_args()
    # resolve all paths, absolute or repo-relative
    run_metadata_path = project_path(args.run_metadata)
    tracking_npz = project_path(args.tracking_npz)
    runup_accel_csv = project_path(args.runup_accel_csv)
    calibration_accel_csv = project_path(args.calibration_accel_csv)
    output_dir = project_path(args.output_dir)
    if (
        run_metadata_path is None
        or tracking_npz is None
        or runup_accel_csv is None
        or calibration_accel_csv is None
        or output_dir is None
    ):
        raise SystemExit("One or more paths could not be resolved.")
    for path, label in (
        (run_metadata_path, "run metadata"),
        (tracking_npz, "tracking NPZ"),
        (runup_accel_csv, "run-up accelerometer CSV"),
        (calibration_accel_csv, "calibration accelerometer CSV"),
    ):
        if not path.exists():
            raise FileNotFoundError(f"Missing {label}: {path}")

    output_dir.mkdir(parents=True, exist_ok=True)
    run_metadata = load_yaml(run_metadata_path)
    video_path = project_path(run_metadata.get("video_path"))

    # nominal values come from metadata
    # accelerometer can override the drive frequency below
    nominal_drive_hz = metadata_drive_hz(run_metadata)
    nominal_expected_subharmonic_hz = metadata_expected_subharmonic_hz(run_metadata, nominal_drive_hz)

    # accelerometer gives measured drive frequency and gamma envelope
    accel = analyze_accelerometer(
        runup_csv=runup_accel_csv,
        calibration_csv=calibration_accel_csv,
        drive_hz=nominal_drive_hz,
        window_s=float(args.accel_lockin_window_s),
        auto_search_min_hz=float(args.accel_auto_search_min_hz),
        auto_search_max_hz=float(args.accel_auto_search_max_hz),
        accel_time_offset_s=float(args.accel_time_offset_s),
    )
    frequency_selection = choose_analysis_frequencies(
        nominal_drive_hz=nominal_drive_hz,
        nominal_expected_subharmonic_hz=nominal_expected_subharmonic_hz,
        measured_drive_hz=float(accel["measured_drive_frequency_hz"]),
        source=str(args.video_frequency_source),
    )
    analysis_drive_hz = float(frequency_selection["analysis_drive_hz"])
    expected_subharmonic_hz = float(frequency_selection["analysis_expected_subharmonic_hz"])

    # load video dot motion and scan only near expected subharmonic
    tracking = load_tracking_displacements(
        tracking_npz,
        min_valid_dot_fraction=float(args.min_valid_dot_fraction),
        baseline_seconds=float(args.baseline_video_seconds),
    )
    time_s = tracking["time_s"]
    freqs_hz = np.arange(
        max(0.05, expected_subharmonic_hz - float(args.subharmonic_half_width_hz)),
        expected_subharmonic_hz + float(args.subharmonic_half_width_hz) + 0.5 * float(args.frequency_step_hz),
        float(args.frequency_step_hz),
    )
    band_power = lockin_band_power(
        dxy_px=tracking["dxy_px"],
        valid=tracking["valid"],
        times_s=time_s,
        frequencies_hz=freqs_hz,
        window_s=float(args.lockin_window_s),
    )

    # main envelope is the strongest power inside the subharmonic band
    # also save the exact f_d/2 bin separately
    best_idx = np.nanargmax(band_power, axis=1)
    best_power = band_power[np.arange(len(time_s)), best_idx]
    best_freq_hz = freqs_hz[best_idx]
    exact_idx = int(np.nanargmin(np.abs(freqs_hz - expected_subharmonic_hz)))
    exact_power = band_power[:, exact_idx]
    envelope_px = np.sqrt(np.maximum(best_power, 0.0))
    exact_envelope_px = np.sqrt(np.maximum(exact_power, 0.0))

    baseline_mask = time_s <= float(args.baseline_video_seconds)
    if int(np.sum(baseline_mask)) < 5:
        baseline_mask = np.arange(len(time_s)) < min(30, len(time_s))
    baseline_envelope_px = float(np.nanmedian(envelope_px[baseline_mask]))
    finite_envelope = envelope_px[np.isfinite(envelope_px)]
    noise_floor_px = float(np.nanpercentile(finite_envelope, 5)) if finite_envelope.size else 1e-9
    noise_floor_px = max(noise_floor_px, 1e-9)
    # log10 excess is just a visual/review metric
    # not an automatic onset decision
    log10_excess_px = np.log10(np.maximum(envelope_px - baseline_envelope_px + noise_floor_px, noise_floor_px))

    # interpolate gamma onto video frame times
    gamma_interpolated_g = np.interp(
        time_s,
        accel["time_s"],
        accel["gamma_vector_measured_drive_g"],
        left=float("nan"),
        right=float("nan"),
    )

    video_metrics = pd.DataFrame(
        # one row per video frame, this is what the manual selector reads
        {
            "frame_index": tracking["frame_indices"],
            "time_s": time_s,
            "rms_displacement_px": tracking["rms_displacement_px"],
            "subharmonic_band_envelope_px": envelope_px,
            "subharmonic_band_power_px2": best_power,
            "exact_subharmonic_envelope_px": exact_envelope_px,
            "exact_subharmonic_power_px2": exact_power,
            "best_frequency_hz": best_freq_hz,
            "gamma_interpolated_g": gamma_interpolated_g,
            "log10_excess_px": log10_excess_px,
            "valid_dot_fraction": tracking["valid_fraction_frame"],
        }
    )
    video_metrics_path = output_dir / "video_onset_metrics.csv"
    video_metrics.to_csv(video_metrics_path, index=False)

    # outputs for the manual selector
    # csv = per time samples, npz = full band power, png = quick plots
    lockin_npz_path = output_dir / "subharmonic_lockin_band_power.npz"
    np.savez_compressed(
        lockin_npz_path,
        time_s=time_s.astype(np.float64),
        frequencies_hz=freqs_hz.astype(np.float64),
        power_px2=band_power.astype(np.float32),
        best_frequency_hz=best_freq_hz.astype(np.float64),
        best_power_px2=best_power.astype(np.float64),
        exact_frequency_hz=np.array(float(freqs_hz[exact_idx])),
        exact_power_px2=exact_power.astype(np.float64),
    )

    accel_metrics_path = output_dir / "accelerometer_gamma_metrics.csv"
    accel["accel_metrics"].to_csv(accel_metrics_path, index=False)
    plot_lockin_map(
        output_dir / "subharmonic_lockin_band_power.png",
        time_s=time_s,
        freqs_hz=freqs_hz,
        power=band_power,
        best_freq_hz=best_freq_hz,
        expected_hz=expected_subharmonic_hz,
    )
    plot_synchronized_summary(
        output_dir / "manual_onset_review.png",
        video_time_s=time_s,
        envelope_px=envelope_px,
        exact_envelope_px=exact_envelope_px,
        best_frequency_hz=best_freq_hz,
        expected_hz=expected_subharmonic_hz,
        accel_time_s=accel["time_s"],
        gamma_g=accel["gamma_vector_measured_drive_g"],
    )

    tracking_summary_path = tracking_npz.parent / "tracking_summary.json"
    tracking_summary = {}
    if tracking_summary_path.exists():
        tracking_summary = json.loads(tracking_summary_path.read_text(encoding="utf-8"))

    # summary json ties together inputs, choices, quality metrics and output paths
    summary = {
        # this is the manifest the streamlit selector uses
        "schema": "runup_onset_review_metrics_v1",
        "run_metadata": relpath(run_metadata_path),
        "video_path": relpath(video_path),
        "tracking_npz": relpath(tracking_npz),
        "runup_accelerometer_csv": relpath(runup_accel_csv),
        "calibration_accelerometer_csv": relpath(calibration_accel_csv),
        "drive_frequency_hz": analysis_drive_hz,
        "nominal_drive_frequency_hz": nominal_drive_hz,
        "expected_subharmonic_hz": float(expected_subharmonic_hz),
        "nominal_expected_subharmonic_hz": nominal_expected_subharmonic_hz,
        "video_frequency_selection": frequency_selection,
        "video_timebase": summarize_timebase(time_s),
        "tracking": {
            "dots_used": int(tracking["dots_total_after_filter"]),
            "min_valid_dot_fraction": float(args.min_valid_dot_fraction),
            "median_frame_valid_fraction": float(np.nanmedian(tracking["valid_fraction_frame"])),
            "tracking_summary": tracking_summary,
        },
        "video_metric": {
            "metric": "max signed-displacement lock-in envelope inside the subharmonic band",
            "baseline_video_seconds": float(args.baseline_video_seconds),
            "baseline_envelope_px": baseline_envelope_px,
            "log10_noise_floor_px": float(np.log10(noise_floor_px)),
            "lockin_window_s": float(args.lockin_window_s),
            "subharmonic_band_half_width_hz": float(args.subharmonic_half_width_hz),
            "frequency_step_hz": float(args.frequency_step_hz),
        },
        "accelerometer": {
            "time_offset_s": float(args.accel_time_offset_s),
            "gamma_method": "bias-corrected three-axis lock-in norm at the measured drive-band peak",
            "calibration_bias_xyz_g": accel["calibration_bias_xyz_g"].astype(float).tolist(),
            "nominal_drive_frequency_hz": nominal_drive_hz,
            "measured_drive_frequency_hz": float(accel["measured_drive_frequency_hz"]),
            "nominal_projection_axis_xyz": accel["projection_axis_xyz"].astype(float).tolist(),
            "measured_drive_projection_axis_xyz": accel["measured_drive_projection_axis_xyz"].astype(float).tolist(),
            "vector_global_peak": accel["vector_global_peak"],
            "vector_drive_band_peak": accel["vector_drive_band_peak"],
            "vector_double_drive_band_peak": accel["vector_double_drive_band_peak"],
            "calibration_gamma_vector_nominal_drive_median_g": float(
                np.nanmedian(accel["calibration_gamma_vector_nominal_drive_g"])
            ),
            "calibration_gamma_vector_nominal_drive_p95_g": float(
                np.nanpercentile(accel["calibration_gamma_vector_nominal_drive_g"], 95)
            ),
            "calibration_gamma_vector_measured_drive_median_g": float(
                np.nanmedian(accel["calibration_gamma_vector_measured_drive_g"])
            ),
            "calibration_gamma_vector_measured_drive_p95_g": float(
                np.nanpercentile(accel["calibration_gamma_vector_measured_drive_g"], 95)
            ),
        },
        "outputs": {
            "video_metrics_csv": relpath(video_metrics_path),
            "lockin_power_npz": relpath(lockin_npz_path),
            "lockin_power_plot": relpath(output_dir / "subharmonic_lockin_band_power.png"),
            "accelerometer_metrics_csv": relpath(accel_metrics_path),
            "manual_review_plot": relpath(output_dir / "manual_onset_review.png"),
        },
    }
    summary_path = output_dir / "onset_review_summary.json"
    write_json(summary_path, summary)

    print(f"Saved {relpath(summary_path)}")
    print(f"Saved {relpath(video_metrics_path)}")
    print(f"Saved {relpath(accel_metrics_path)}")


if __name__ == "__main__":
    main()
