#!/usr/bin/env python3


# this takes tracked metric dot displacement
# converts it into surface gradients
# and then integrates those gradients into signed height maps

from pathlib import Path
import argparse
import json
import math
import warnings

import numpy as np
import pandas as pd
import yaml

from scipy.interpolate import griddata
from scipy import sparse
from scipy.sparse.linalg import lsqr

try:
    from scipy.ndimage import gaussian_filter
except Exception:
    gaussian_filter = None


def guess_project_root() -> Path:
    # repo root from this script location
    return Path(__file__).resolve().parents[2]


def relpath(path: Path, root: Path) -> str:
    # use repo-relative paths in summaries where possible.
    path = Path(path)
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except Exception:
        return str(path)


def project_path(path_like, root: Path) -> Path:
    # keep metadata/output paths relative to the public repo root when possible
    p = Path(path_like)
    return p if p.is_absolute() else root / p


PROJECT_ROOT = guess_project_root()
# reconstruction constants
# these keep the public script narrow and fixed rather than full of cli knobs
USE_CORRECTED_DISPLACEMENTS = True
BASELINE_SUBTRACTION_MODE = "temporal_median"
FRAME_STRIDE_FOR_RECONSTRUCTION = 1
MIN_VALID_DOT_FRACTION = 0.30
GRID_STEP_M = None
GRID_STEP_FACTOR_RELATIVE_TO_DOT_SPACING = 1.0
CROP_MARGIN_FRACTION = 0.03
INTERPOLATION_METHOD = "linear"
FILL_NAN_WITH_NEAREST = True
SMOOTH_GRADIENTS = True
SMOOTH_SIGMA_GRID_CELLS = 0.6
USE_SURFACE_POINT_CORRECTION = True
LSQR_ATOL = 1e-9
LSQR_BTOL = 1e-9
LSQR_ITER_LIM = 2000


# what this expects:
# one run metadata file that points to tracked_dots_fsss.npz and the
# raytrace_fsss_calibration.json used to convert dot motion into gradients
def parse_args() -> argparse.Namespace:
    # one run metadata file is enough because batch_full_fsss.py writes all
    # paths needed by this script into that file.
    parser = argparse.ArgumentParser(description="Reconstruct metric FSSS surface height maps from tracked dots.")
    parser.add_argument("run_metadata", help="metadata_run.yaml for one FSSS run.")
    parser.add_argument("--max-frames", type=int, default=None)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    # resolve and load run metadata generated by batch_full_fsss.py.
    RUN_METADATA_PATH = project_path(args.run_metadata, PROJECT_ROOT)
    if not RUN_METADATA_PATH.exists():
        raise FileNotFoundError(f"Missing run metadata: {RUN_METADATA_PATH}")

    with RUN_METADATA_PATH.open("r", encoding="utf-8") as f:
        run_metadata = yaml.safe_load(f)

    RUN_ID = run_metadata["run_id"]
    CALIBRATION_ID = run_metadata["calibration_id"]

    calib_output_declared = run_metadata.get("calibration_output_dir", f"outputs/full_fsss/calibration/{CALIBRATION_ID}")
    CALIBRATION_OUTPUT_DIR = project_path(calib_output_declared, PROJECT_ROOT)
    run_output_declared = run_metadata.get("run_output_dir", f"outputs/full_fsss/runs/{RUN_ID}")
    RUN_OUTPUT_DIR = project_path(run_output_declared, PROJECT_ROOT)
    TRACKING_OUTPUT_DIR = RUN_OUTPUT_DIR / "tracking"
    RECON_OUTPUT_DIR = RUN_OUTPUT_DIR / "reconstruction"
    RECON_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    TRACKING_npz_PATH = TRACKING_OUTPUT_DIR / "tracked_dots_fsss.npz"
    RAYTRACE_CAL_PATH = CALIBRATION_OUTPUT_DIR / "raytrace_fsss_calibration.json"

    for p in [TRACKING_npz_PATH, RAYTRACE_CAL_PATH]:
        if not p.exists():
            raise FileNotFoundError(f"Missing required input: {p}")

    with RAYTRACE_CAL_PATH.open("r", encoding="utf-8") as f:
        # raytrace calibration provides B and optional surface-point correction L.
        ray_cal = json.load(f)

    tracking = np.load(TRACKING_npz_PATH, allow_pickle=True)
    max_frames_to_reconstruct = args.max_frames

    # load arrays from tracking npz. fsss tracking has already converted pixels
    # into object-plane displacements and applied metric affine subtraction.
    frame_indices_all = tracking["frame_indices"].astype(int)
    time_s_all = tracking["time_s"].astype(float)

    tracking_timebase_source = str(tracking["timestamp_source"]) if "timestamp_source" in tracking.files else "unknown"
    try:
        tracking_timebase_summary = json.loads(str(tracking["timebase_summary_json"])) if "timebase_summary_json" in tracking.files else {}
    except Exception:
        tracking_timebase_summary = {}
    x_ref_m = tracking["x_ref_obj_m"].astype(float)
    y_ref_m = tracking["y_ref_obj_m"].astype(float)
    # valid_final is the final mask after template matching, affine correction,
    # object displacement bounds, and neighbor filtering.
    valid_all = tracking["valid_final"].astype(bool)

    if USE_CORRECTED_DISPLACEMENTS:
        # normal mode: use affine-corrected metric displacement.
        dx_obj_m_all = tracking["dx_obj_corrected_m"].astype(float)
        dy_obj_m_all = tracking["dy_obj_corrected_m"].astype(float)
        displacement_label = "affine-corrected"
    else:
        # ablation/debug mode: use raw object-plane displacement.
        dx_obj_m_all = tracking["dx_obj_raw_m"].astype(float)
        dy_obj_m_all = tracking["dy_obj_raw_m"].astype(float)
        displacement_label = "raw"

    n_frames_total, n_dots = dx_obj_m_all.shape
    valid_fraction_all = valid_all.mean(axis=1)

    # per-dot temporal baseline subtraction removes static offsets in the
    # tracked displacement field before converting displacement to surface slope.
    if BASELINE_SUBTRACTION_MODE == "temporal_median":
        # compute each dot's median displacement over valid frames. This removes
        # static offsets before converting displacement to slope.
        dx_for_baseline = np.where(valid_all & np.isfinite(dx_obj_m_all), dx_obj_m_all, np.nan)
        dy_for_baseline = np.where(valid_all & np.isfinite(dy_obj_m_all), dy_obj_m_all, np.nan)
        baseline_dx_obj_m = np.nanmedian(dx_for_baseline, axis=0)
        baseline_dy_obj_m = np.nanmedian(dy_for_baseline, axis=0)
        baseline_dx_obj_m = np.nan_to_num(baseline_dx_obj_m, nan=0.0)
        baseline_dy_obj_m = np.nan_to_num(baseline_dy_obj_m, nan=0.0)
        dx_obj_m_all = dx_obj_m_all - baseline_dx_obj_m[None, :]
        dy_obj_m_all = dy_obj_m_all - baseline_dy_obj_m[None, :]
        displacement_label = f"{displacement_label} minus per-dot temporal median"
    elif BASELINE_SUBTRACTION_MODE == "none":
        baseline_dx_obj_m = np.zeros(n_dots, dtype=float)
        baseline_dy_obj_m = np.zeros(n_dots, dtype=float)
    else:
        raise ValueError("BASELINE_SUBTRACTION_MODE must be 'none' or 'temporal_median'.")

    candidate_frame_positions = np.arange(0, n_frames_total, max(1, int(FRAME_STRIDE_FOR_RECONSTRUCTION)), dtype=int)
    # reconstruct only frames with enough valid dots.
    candidate_frame_positions = candidate_frame_positions[valid_fraction_all[candidate_frame_positions] >= MIN_VALID_DOT_FRACTION]
    if max_frames_to_reconstruct is not None and len(candidate_frame_positions) > int(max_frames_to_reconstruct):
        candidate_frame_positions = candidate_frame_positions[:int(max_frames_to_reconstruct)]

    if len(candidate_frame_positions) == 0:
        raise RuntimeError("No frames selected for reconstruction. Lower MIN_VALID_DOT_FRACTION or inspect tracking quality.")

    # ray-traced calibration matrices: B maps object-plane dot displacement to
    # surface gradients; L optionally shifts each dot to the surface point it
    # actually probes.
    B = np.array(ray_cal["fit"]["B_displacement_to_gradient_1_per_m"], dtype=float)
    # B maps [dx_obj, dy_obj] to [dz/dx, dz/dy].
    L = np.array(ray_cal.get("surface_point_correction", {}).get("L_surface_point_correction_dimensionless", [[0, 0], [0, 0]]), dtype=float)
    # L maps apparent object displacement to a small shift in where the ray
    # probes the surface.

    valid_disp_range = ray_cal["fit"].get("valid_displacement_range", {})
    if valid_disp_range:
        p95_cal_disp_mm = valid_disp_range.get("p95_delta_obj_magnitude_m", np.nan) * 1000
        max_cal_disp_mm = valid_disp_range.get("max_delta_obj_magnitude_m", np.nan) * 1000
        measured_disp_mm = np.sqrt(dx_obj_m_all**2 + dy_obj_m_all**2) * 1000
        # warn if real measured displacements exceed the synthetic calibration
        # range used to fit B.
        p95_meas = float(np.nanpercentile(measured_disp_mm[valid_all], 95)) if valid_all.any() else np.nan
        if np.isfinite(max_cal_disp_mm) and p95_meas > max_cal_disp_mm:
            warnings.warn(
                "Measured dot displacements exceed the maximum synthetic calibration displacement. "
                "The linear ray calibration may be extrapolating."
            )

    # estimate dot spacing in metres from reference grid.
    xy_ref = np.column_stack([x_ref_m, y_ref_m])
    try:
        from scipy.spatial import cKDTree
        tree = cKDTree(xy_ref)
        # median nearest-neighbor distance estimates physical dot spacing.
        dists, _ = tree.query(xy_ref, k=2)
        dot_spacing_m = float(np.nanmedian(dists[:, 1]))
    except Exception:
        dot_spacing_m = 1e-3

    if GRID_STEP_M is None:
        # default reconstruction grid spacing is one dot spacing.
        grid_step_m = dot_spacing_m * GRID_STEP_FACTOR_RELATIVE_TO_DOT_SPACING
    else:
        grid_step_m = float(GRID_STEP_M)

    # regular reconstruction grid: crop slightly inside the tracked dot domain
    # to reduce interpolation artifacts at the boundary.
    x_min, x_max = float(np.nanmin(x_ref_m)), float(np.nanmax(x_ref_m))
    y_min, y_max = float(np.nanmin(y_ref_m)), float(np.nanmax(y_ref_m))
    x_margin = (x_max - x_min) * CROP_MARGIN_FRACTION
    y_margin = (y_max - y_min) * CROP_MARGIN_FRACTION

    x_grid_vec = np.arange(x_min + x_margin, x_max - x_margin + 0.5*grid_step_m, grid_step_m)
    y_grid_vec = np.arange(y_min + y_margin, y_max - y_margin + 0.5*grid_step_m, grid_step_m)
    Xg, Yg = np.meshgrid(x_grid_vec, y_grid_vec)

    ny, nx = Xg.shape

    print(
        f"Reconstructing {RUN_ID}: {len(candidate_frame_positions)} frame(s), "
        f"{n_dots} dots, grid {ny}x{nx}, {displacement_label}."
    )

    # convert each dot's measured object-plane displacement into p=dz/dx and
    # q=dz/dy using the ray-traced B matrix.
    def compute_gradients_from_displacements(dx_m, dy_m):
        # build N x 2 displacement matrix, then multiply by B.T so each dot
        # yields p=dz/dx and q=dz/dy.
        dxy = np.column_stack([dx_m, dy_m])
        grad = dxy @ B.T
        return grad[:, 0], grad[:, 1]

    # surface-point correction applies the L matrix so gradients are scattered
    # at the estimated probed surface coordinates rather than the flat dot
    # reference coordinates.
    def surface_points_from_displacements(dx_m, dy_m):
        # by default gradients are assigned to corrected surface probe locations,
        # not exactly to the flat reference dot coordinates.
        dxy = np.column_stack([dx_m, dy_m])
        if USE_SURFACE_POINT_CORRECTION:
            shift = dxy @ L.T
        else:
            shift = np.zeros_like(dxy)
        xs = x_ref_m + shift[:, 0]
        ys = y_ref_m + shift[:, 1]
        return xs, ys

    # interpolate scattered dot gradients onto the regular grid. Nearest filling
    # and light Gaussian smoothing keep the subsequent integration well posed.
    def interpolate_gradient_to_grid(xs, ys, p, q, valid):
        # scattered dot gradients live at irregular dot/surface probe positions.
        # griddata interpolates them onto the regular reconstruction grid.
        pts = np.column_stack([xs[valid], ys[valid]])
        pvals = p[valid]
        qvals = q[valid]

        if len(pts) < 10:
            return np.full_like(Xg, np.nan, dtype=float), np.full_like(Xg, np.nan, dtype=float)

        Pg = griddata(pts, pvals, (Xg, Yg), method=INTERPOLATION_METHOD)
        Qg = griddata(pts, qvals, (Xg, Yg), method=INTERPOLATION_METHOD)

        if FILL_NAN_WITH_NEAREST and (np.isnan(Pg).any() or np.isnan(Qg).any()):
            # linear interpolation is nan outside the convex hull. Nearest fill
            # avoids holes before integration.
            Pg_near = griddata(pts, pvals, (Xg, Yg), method="nearest")
            Qg_near = griddata(pts, qvals, (Xg, Yg), method="nearest")
            Pg = np.where(np.isnan(Pg), Pg_near, Pg)
            Qg = np.where(np.isnan(Qg), Qg_near, Qg)

        if SMOOTH_GRADIENTS and gaussian_filter is not None and SMOOTH_SIGMA_GRID_CELLS > 0:
            # light Gaussian smoothing damps dot-scale interpolation noise in
            # the gradient field before integration.
            Pg = gaussian_filter(Pg, sigma=SMOOTH_SIGMA_GRID_CELLS, mode="nearest")
            Qg = gaussian_filter(Qg, sigma=SMOOTH_SIGMA_GRID_CELLS, mode="nearest")

        return Pg, Qg


    # ## gradient-field integration
    # 
    # the measured field is:
    # 
    # \[
    # p(x,y)=\partial_x \zeta,\qquad q(x,y)=\partial_y \zeta.
    # \]
    # 
    # we reconstruct \(\zeta\) by solving the least-squares problem:
    # 
    # \[
    # \min_\zeta \sum \left[(D_x\zeta-p)^2+(D_y\zeta-q)^2\right].
    # \]
    # 
    # the height offset is arbitrary, so the reconstruction sets the mean surface height to zero.
    # 



    # sparse finite-difference system for the least-squares integration problem.
    # the final row fixes the arbitrary height offset by enforcing mean height 0.
    def build_gradient_integration_matrix(ny, nx, dx, dy):
        # build sparse matrix A such that A @ z approximates gradient constraints.
        # unknown vector z is the flattened height map with ny*nx entries.
        n_unknown = ny * nx
        rows = []
        cols = []
        data = []
        row = 0
        rhs_info = []

        def idx(j, i):
            # flatten 2D grid index (j row, i column) to 1D unknown index.
            return j * nx + i

        # x-gradient constraints.
        for j in range(ny):
            for i in range(nx - 1):
                # z[j,i+1] - z[j,i] = p_edge * dx.
                rows.extend([row, row])
                cols.extend([idx(j, i+1), idx(j, i)])
                data.extend([1.0, -1.0])
                rhs_info.append(("x", j, i))
                row += 1

        # y-gradient constraints.
        for j in range(ny - 1):
            for i in range(nx):
                # z[j+1,i] - z[j,i] = q_edge * dy.
                rows.extend([row, row])
                cols.extend([idx(j+1, i), idx(j, i)])
                data.extend([1.0, -1.0])
                rhs_info.append(("y", j, i))
                row += 1

        # mean-zero constraint fixes the nullspace.
        # gradient constraints determine height only up to an additive constant.
        mean_weight = 1.0 / math.sqrt(n_unknown)
        for k in range(n_unknown):
            rows.append(row)
            cols.append(k)
            data.append(mean_weight)
        rhs_info.append(("mean_zero", -1, -1))
        row += 1

        A = sparse.csr_matrix((data, (rows, cols)), shape=(row, n_unknown))
        # rhs_info records which physical equation each row of A represents so
        # the RHS can be built frame-by-frame from Pg/Qg.
        return A, rhs_info

    # build the right-hand side from edge-averaged gradients so each finite
    # difference equation constrains the height difference across one grid edge.
    def build_rhs_from_gradients(Pg, Qg, dx, dy, rhs_info):
        # convert gradient samples into height-difference constraints.
        b = np.zeros(len(rhs_info), dtype=float)
        for r, item in enumerate(rhs_info):
            kind, j, i = item
            if kind == "x":
                # edge gradient is average of the two neighboring p samples.
                p_edge = 0.5 * (Pg[j, i] + Pg[j, i+1])
                b[r] = p_edge * dx
            elif kind == "y":
                # edge gradient is average of the two neighboring q samples.
                q_edge = 0.5 * (Qg[j, i] + Qg[j+1, i])
                b[r] = q_edge * dy
            elif kind == "mean_zero":
                b[r] = 0.0
        return b

    dx_grid = float(np.mean(np.diff(x_grid_vec)))
    dy_grid = float(np.mean(np.diff(y_grid_vec)))

    A_int, rhs_info = build_gradient_integration_matrix(ny, nx, dx_grid, dy_grid)

    # solve for signed surface height with scipy.sparse.linalg.lsqr, then remove
    # any residual mean offset.
    def integrate_gradient_field(Pg, Qg):
        # solve the sparse overdetermined least-squares system A z ~= b.
        b = build_rhs_from_gradients(Pg, Qg, dx_grid, dy_grid, rhs_info)
        result = lsqr(A_int, b, atol=LSQR_ATOL, btol=LSQR_BTOL, iter_lim=LSQR_ITER_LIM)
        z = result[0].reshape(ny, nx)
        # remove any numerical residual mean after solving.
        z = z - np.nanmean(z)
        diagnostics = {
            "istop": int(result[1]),
            "itn": int(result[2]),
            "r1norm": float(result[3]),
            "r2norm": float(result[4]),
            "anorm": float(result[5]),
            "acond": float(result[6]),
        }
        return z, diagnostics

    # curl is a sanity check for the gradient field
    # if p and q really came from one height surface, curl should be close to zero
    def curl_integrability_error(Pg, Qg):
        # compute approximate curl: ∂p/∂y - ∂q/∂x.
        # if Pg,Qg came from an exact scalar height field, this would be zero.
        dp_dy = np.gradient(Pg, dy_grid, axis=0)
        dq_dx = np.gradient(Qg, dx_grid, axis=1)
        curl = dp_dy - dq_dx
        return curl




    # for each useful frame:
    # turn displacement into gradients, interpolate, integrate height,
    # measure quality, and store the reconstructed surface
    selected_positions = candidate_frame_positions
    n_recon = len(selected_positions)

    grad_x_all = np.full((n_recon, ny, nx), np.nan, dtype=np.float32)
    grad_y_all = np.full((n_recon, ny, nx), np.nan, dtype=np.float32)
    zeta_m_all = np.full((n_recon, ny, nx), np.nan, dtype=np.float32)
    curl_all = np.full((n_recon, ny, nx), np.nan, dtype=np.float32)

    recon_rows = []

    for out_idx, frame_pos in enumerate(selected_positions):
        # pull one frame of tracked displacement and validity.
        dx_m = dx_obj_m_all[frame_pos]
        dy_m = dy_obj_m_all[frame_pos]
        valid = valid_all[frame_pos].copy()
        valid &= np.isfinite(dx_m) & np.isfinite(dy_m)

        p, q = compute_gradients_from_displacements(dx_m, dy_m)
        xs, ys = surface_points_from_displacements(dx_m, dy_m)

        # final valid mask requires finite gradients and finite surface probe
        # coordinates.
        valid &= np.isfinite(p) & np.isfinite(q) & np.isfinite(xs) & np.isfinite(ys)

        Pg, Qg = interpolate_gradient_to_grid(xs, ys, p, q, valid)
        if np.isnan(Pg).any() or np.isnan(Qg).any():
            warnings.warn(f"Frame {frame_pos} still has nans after interpolation; filling with zeros.")
            Pg = np.nan_to_num(Pg, nan=0.0)
            Qg = np.nan_to_num(Qg, nan=0.0)

        Z, diag = integrate_gradient_field(Pg, Qg)
        curl = curl_integrability_error(Pg, Qg)

        # store full grid fields in frame-major arrays.
        grad_x_all[out_idx] = Pg
        grad_y_all[out_idx] = Qg
        zeta_m_all[out_idx] = Z
        curl_all[out_idx] = curl

        recon_rows.append({
            # quality row is one reconstructed frame. These values let later
            # scripts choose representative frames and diagnose integration.
            "output_frame_position": int(out_idx),
            "tracking_frame_position": int(frame_pos),
            "frame_index": int(frame_indices_all[frame_pos]),
            "time_s": float(time_s_all[frame_pos]),
            "valid_dot_fraction": float(valid.mean()),
            "zeta_rms_m": float(np.sqrt(np.mean(Z**2))),
            "zeta_peak_to_peak_m": float(np.nanmax(Z) - np.nanmin(Z)),
            "zeta_min_m": float(np.nanmin(Z)),
            "zeta_max_m": float(np.nanmax(Z)),
            "grad_rms": float(np.sqrt(np.nanmean(Pg**2 + Qg**2))),
            "curl_rms_1_per_m": float(np.sqrt(np.nanmean(curl**2))),
            **{f"lsqr_{k}": v for k, v in diag.items()},
        })

    recon_quality = pd.DataFrame(recon_rows)

    # what this writes:
    # the npz keeps the metric grids, gradients, reconstructed heights, curl,
    # and calibration matrices
    # the csv is just the per-frame quality summary
    recon_npz_path = RECON_OUTPUT_DIR / "surface_height_m.npz"
    quality_path = RECON_OUTPUT_DIR / "surface_reconstruction_quality.csv"

    np.savez_compressed(
        recon_npz_path,
        # scalar values and where this result came from
        run_id=np.array(RUN_ID),
        calibration_id=np.array(CALIBRATION_ID),
        selected_tracking_frame_positions=selected_positions.astype(int),
        frame_indices=frame_indices_all[selected_positions].astype(int),
        time_s=time_s_all[selected_positions].astype(float),
        timestamp_source=np.array(tracking_timebase_source),
        timebase_summary_json=np.array(json.dumps(tracking_timebase_summary)),
        x_grid_m=x_grid_vec.astype(float),
        y_grid_m=y_grid_vec.astype(float),
        # regular metric grid.
        X_m=Xg.astype(float),
        Y_m=Yg.astype(float),
        grad_x=grad_x_all,
        grad_y=grad_y_all,
        # signed reconstructed surface height in meters.
        zeta_m=zeta_m_all,
        curl_1_per_m=curl_all,
        B_displacement_to_gradient_1_per_m=B,
        L_surface_point_correction=L,
        use_corrected_displacements=np.array(USE_CORRECTED_DISPLACEMENTS),
        baseline_subtraction_mode=np.array(BASELINE_SUBTRACTION_MODE),
        baseline_dx_obj_m=baseline_dx_obj_m.astype(float),
        baseline_dy_obj_m=baseline_dy_obj_m.astype(float),
        use_surface_point_correction=np.array(USE_SURFACE_POINT_CORRECTION),
    )

    recon_quality.to_csv(quality_path, index=False)

    print(f"Saved {relpath(recon_npz_path, PROJECT_ROOT)}")
    print(f"Saved {relpath(quality_path, PROJECT_ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
